---
containers:
  mongo:
    repo: docker.io/mongo
    tag: 7.0.29
  photoprism:
    repo: photoprism/photoprism
    tag: 251130
  photoprism_mariadb:
    repo: mariadb
    tag: 11.8.5
  homeassistant:
    repo: ghcr.io/home-assistant/home-assistant
    tag: 2026.1.3
  ha_mariadb:
    repo: mariadb
    tag: 10.11.15
  zigbee2mqtt:
    repo: koenkk/zigbee2mqtt
    tag: 2.7.2
  mosquitto:
    repo: eclipse-mosquitto
    tag: 2.0.22
  cloudflared:
    repo: cloudflare/cloudflared
    tag: 2026.1.2
  pihole:
    repo: pihole/pihole
    tag: 2025.11.1
  smokeping:
    repo: quay.io/linuxserver.io/smokeping
    tag: 2.9.0
  syncthing:
    repo: syncthing/syncthing
    tag: 1.30.0
  traefik:
    repo: traefik
    tag: v3.6.7
  whisper:
    repo: rhasspy/wyoming-whisper
    tag: 3.1.0
  piper:
    repo: rhasspy/wyoming-piper
    tag: 2.2.1
  victoriametrics:
    repo: victoriametrics/victoria-metrics
    tag: v1.134.0
  grafana:
    repo: grafana/grafana
    tag: 12.3.2
  nodeexporter:
    repo: prom/node-exporter
    tag: v1.10.2
  minecraft:
    repo: itzg/minecraft-server
    tag: 2026.1.3
  jellyfin:
    repo: jellyfin/jellyfin
    tag: 10.11.6
  semaphore:
    repo: semaphoreui/semaphore
    tag: v2.16.51
  semaphore_db:
    repo: mariadb
    tag: 11.8.5
  changedetection:
    repo: ghcr.io/dgtlmoon/changedetection.io
    tag: 0.52.9
  browserless_chromium:
    repo: ghcr.io/browserless/chromium
    tag: v2.38.4
  forgejo:
    repo: codeberg.org/forgejo/forgejo
    tag: 14.0.1-rootless
