---
containers:
  unifi:
    repo: lscr.io/linuxserver/unifi-network-application
    tag: 9.3.45-ls100
  mongo:
    repo: docker.io/mongo
    tag: 7.0.26
  photoprism:
    repo: photoprism/photoprism
    tag: "250426"
  photoprism_mariadb:
    repo: mariadb
    tag: 11.8.5
  homeassistant:
    repo: ghcr.io/home-assistant/home-assistant
    tag: 2025.12.1
  ha_mariadb:
    repo: mariadb
    tag: 10.11.15
  zigbee2mqtt:
    repo: koenkk/zigbee2mqtt
    tag: 2.7.0
  mosquitto:
    repo: eclipse-mosquitto
    tag: 2.0.22
  cloudflared:
    repo: cloudflare/cloudflared
    tag: 2025.11.1
  pihole:
    repo: pihole/pihole
    tag: 2025.11.1
  smokeping:
    repo: quay.io/linuxserver.io/smokeping
    tag: 2.9.0
  syncthing:
    repo: syncthing/syncthing
    tag: 1.30.0
  traefik:
    repo: traefik
    tag: v2.11.32
  whisper:
    repo: rhasspy/wyoming-whisper
    tag: 3.0.2
  piper:
    repo: rhasspy/wyoming-piper
    tag: 2.1.2
  victoriametrics:
    repo: victoriametrics/victoria-metrics
    tag: v1.131.0
  grafana:
    repo: grafana/grafana
    tag: 12.3.0
  nodeexporter:
    repo: prom/node-exporter
    tag: v1.10.2
  minecraft:
    repo: itzg/minecraft-server
    tag: 2025.10.5
  jellyfin:
    repo: jellyfin/jellyfin
    tag: 10.11.4
  semaphore:
    repo: semaphoreui/semaphore
    tag: v2.16.45
  semaphore_db:
    repo: mariadb
    tag: 11.8.5
