---
containers:
  unifi:
    repo: lscr.io/linuxserver/unifi-network-application
    tag: 9.3.45-ls100
  mongo:
    repo: docker.io/mongo
    tag: 7.0.25
  photoprism:
    repo: photoprism/photoprism
    tag: "250426"
  photoprism_mariadb:
    repo: mariadb
    tag: 11.8.3
  homeassistant:
    repo: ghcr.io/home-assistant/home-assistant
    tag: 2025.10.4
  ha_mariadb:
    repo: mariadb
    tag: 10.11.14
  zigbee2mqtt:
    repo: koenkk/zigbee2mqtt
    tag: 2.6.2
  mosquitto:
    repo: eclipse-mosquitto
    tag: 2.0.22
  cloudflared:
    repo: cloudflare/cloudflared
    tag: 2025.10.0
  pihole:
    repo: pihole/pihole
    tag: 2025.08.0
  smokeping:
    repo: quay.io/linuxserver.io/smokeping
    tag: 2.9.0
  syncthing:
    repo: syncthing/syncthing
    tag: 1.30.0
  traefik:
    repo: traefik
    tag: v2.11.29
  whisper:
    repo: rhasspy/wyoming-whisper
    tag: 2.5.0
  piper:
    repo: rhasspy/wyoming-piper
    tag: 1.6.3
  victoriametrics:
    repo: victoriametrics/victoria-metrics
    tag: v1.128.0
  grafana:
    repo: grafana/grafana
    tag: 12.2.1
  nodeexporter:
    repo: prom/node-exporter
    tag: v1.10.0
  minecraft:
    repo: itzg/minecraft-server
    tag: 2025.10.2
  jellyfin:
    repo: jellyfin/jellyfin
    tag: 10.11.0
  semaphore:
    repo: semaphoreui/semaphore
    tag: v2.16.34
  semaphore_db:
    repo: mariadb
    tag: 11.8.3
